// Rejhan Sabovic
// Viginere Cipher Brute Force Cracker

#include<iostream>
#include <string>
using namespace std;

void shift_brute_force(string);

int main()
{
	string ciphertext = "SVYKPBBMBQIGCEDKWASRYDMLQGFKVYMXCBELNMRSWNKVRSGSVEPVCCHGGDMLQXFKXFOTCBJMBQCNMLCXPKXDYVBCTCXHGXKCSKFDHYIWGXXFOXMGRFOZGCMROHQREIOWNOEPOWZSVRRTJKGCDAGMIYXHNOVDYVKOHGXWCFILZPYIWYDXFOVMIEJCWFKOCCTCKVCKRRRIYDVCYRARENOPJKRCDLCOZGNILMIUOLYFIMPLGCXGWIGXWRBERPSPNLGQLJSKFDWQYQCYJRRIGXXCBIQDMLQTYBXQYJFSWAREPKGROVRRIUKCFOQYXEEOHFSWAKVCOVRYJGXHQEGAOWQDLCZVCTYBSGCRIZKXRVIBKKYSRQDELNXFOQWDLQRIZEMJDYNKVMERBRMQLEAUKPYYLNQYSRJIXFKXFOAYCFMBRYZVGXGCSRQORCQEJDLCDVSDLMPMPKEJNVGNKCCFYMOEBSSXHGCXFKXFOAYCFMBRGXRCGCMBOGXXMZSMBTYBILDWFSWDKXFOVRRIPOZCBILNHYXMCVEJNVGNKCGEQKWRBEUCIJVIPGLMGEQKPQYEJKCNBIYMLCBMPKAYCHPKALDSRRIRRIYDVCPVMWELOEPVCYQIYXHQDEPDIBLCUYVISRELEAUWRKKCKXRRIARERREKDLCKXPOMLXIUISPUAFOVCRIZOKYXXMQEGXIVZIPSILMIGXEADMLQXMYJGXHGXKRRERSXUKWGWTMCWGLPCDSNEVQEIYMEPOIPKGRSRESRYWIPSGYRIAKQCDSCXKJKRBSRYDXFOEEOSDDSKKOCRMQXEKOELNMLRIKKHCRMQNIZEXNVEWSREYXFOPJYERDLCBSWKPRIXFOERBIYVHPSHEOGMXXGXYCNXMLERDPCZVCTYBSGCZEPDMAEPYBPWSRRRIPOZGOAQRIPOGCSZCNFSDLCGEQZSNEPYBAGDLYEHGORAOWFOJMERBPYPDLCBWSMGCCWZIQMFMLQSSDSDVSLNSLDSRRINBSTSRAOWYXHJKXCBMLVMDOJMERBDLCQVCKXCCXQEGAOWQDSSBMLQISBSNO";
	cout << "Decryption of the ciphertext: " << ciphertext << endl;
	shift_brute_force(ciphertext);
	return 0;
}

// Shifts the cipher text by all 25 possible shifts in the English alphabet
void shift_brute_force(string str)
{
	char shift;
	string shifted;
	for (int counter = 1; counter < 26; counter++)
	{
		for (int i = 0; i < str.length(); i++)
		{
			shift = str.at(i);
			if (shift != 32)
			{
				shift += counter;
				if (shift > 90)
				{
					shift -= 26;
				}
			}
				shifted += shift;
		}
		cout << "Shift cipher key: " << counter << " : " << shifted << endl << endl;
		shifted = "";
	}
}
